<?php echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=UTF-8' />
  <title>LouderTechnology - Kumbia Enterprise Framework Instance Admin</title>
  <?php Tag::stylesheetLink('style', true) ?>
  <?php echo Core::stylesheetLinkTags() ?>
  <?php echo Tag::javascriptLibrary('framework/scriptaculous/protoculous') ?>
  <?php echo Core::javascriptBase() ?>
 </head>
 <body>
    <?php print View::getContent(); ?>
 </body>
</html>
