<?php echo Tag::stylesheetLink("ext/resources/css/ext-all"); ?>
<?php echo Tag::javascriptInclude("core/framework/ext/adapter/ext/ext-base"); ?>
<?php echo Tag::javascriptInclude("core/framework/ext/ext-all"); ?>
<?php echo Tag::javascriptInclude("admin/asadmin") ?>
<?php Tag::stylesheetLink("admin/asadmin", true) ?>

<div id="header"><h1>LouderTechnology - Kumbia Enterprise Framework Instance Admin (alpha)</h1></div>

<div id="server-info" style='display:none'>
Servidor: <b><?php echo $_SERVER['SERVER_NAME'] ?></b><br>
Instancia: <b><?php echo Core::getInstanceName() ?></b><br>
Administrador: <b><?php echo $_SERVER['SERVER_ADMIN'] ?></b><br>
SO: <b><?php echo php_uname() ?></b><br>
Espacio Libre en Disco: <b><?php echo ServerInfo::getDiskFreeSpace() ?></b><br>
Versi&oacute;n de Kumbia Enterprise Framework: <b><?php echo Core::FRAMEWORK_VERSION ?></b><br>
Zend Engine: <b><?php echo zend_version() ?></b>
</div>

<div style="display:none;">
	<!-- Start page content -->
	<div id="start-div">
		<div style="float:left;" ><?php echo Tag::image("admin/layout-icon.gif") ?></div>
			<div style="margin-left:100px;">
                <h2>Bienvenido!</h2>
                <p>Desde la consola de instancias de Kumbia Enterprise Framework usted puede
                administrar la informaci&oacute;n de configuraci&oacute;n, revisar logs,
                visualizar el estado de las aplicaciones y muchos otros aspectos.</p>
                <table>
                	<tr>
                		<td width='180' align="right" valign="top"><b>Versi&oacute;n de PHP:</b></td>
                		<td>
                		<?php echo PHP_VERSION ?>
                		</td>
                	</tr>
                	<tr>
                		<td align="right" valign="top"><b>Interface con el Web Server:</b></td>
                		<td><?php echo php_sapi_name() ?></td>
                	</tr>
                	<tr>
                		<td align="right" valign="top"><b>Extensiones de PHP Cargadas:</b></td>
                		<td>
                		<?php echo join(", ", get_loaded_extensions()); ?>
                		</td>
                	</tr>
                	<tr>
                		<td align="right" valign="top"><b>Extensiones de Apache:</b></td>
                		<td>
                		<?php echo join(", ", apache_get_modules()); ?>
                		</td>
                	</tr>
                </table>
            </div>
        </div>
    </div>
</div>