<pre>
<?php echo View::getContent(); ?>
</pre>
<h2>Monitoreo de Aplicaciones</h2>
<table cellspacing="0" id='table-monitor' width="100%">
	<thead>
		<tr style="background:#eeeeee;">
			<th align="center">Aplicaci&oacute;n</th>
			<th align="center">Direcci&oacute;n IP</Th>
			<th align="center">&Uacute;ltima Petici&oacute;n</th>
			<th align="center">URI</th>
			<th align="center">Memoria Utilizada</th>
			<th align="center">Mensaje de Estado</th>
			<th align="center">Estado</th>
		</tr>
	</thead>
	<tbody>
	<?php
	foreach($results as $row){
		if($row['status']==ApplicationMonitor::STATUS_OK){
			$status = "ok.png";
		}
		if($row['status']==ApplicationMonitor::STATUS_ERROR){
			$status = "error.png";
		}
		if($row['status']==ApplicationMonitor::STATUS_WARNING){
			$status = "warning.png";
		}
		$hostname = @gethostbyaddr($row['ipaddress']);
		if($row['lastmessage']!=""){
			$message = wordwrap(stripslashes($row['lastmessage']), 80, "<br>");
			if($row['lastcode']){
				$message.=" (".$row['lastcode'].")";
			}
		} else {
			$message = "";
		}
		echo "<tr>
			<td>{$row['application']}</td>
			<td>$hostname</td>
			<td align='left'>".Helpers::verboseTimeAgo($row['lasttime'])."</td>
			<td>{$row['lasturl']}</td>
			<td>".Helpers::toHuman($row['memoryusage'], 4)."</td>
			<td>{$message}</td>
			<td align='center'>".Tag::image("admin/$status")."</td>
		</tr>";
	}
	?>
	</tbody>
</table>